CPP_DIR = Cpp

CPP_OUTPUT = minstack_cpp

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp ./$(CPP_DIR)/minstack.cpp -o $(CPP_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)