CPP_DIR = Cpp
# C_DIR = C_array

CPP_OUTPUT = sort_cpp
C_OUTPUT = bubblesort_c

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp -o $(CPP_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)