CPP_DIR = Cpp
C_DIR = C

CPP_OUTPUT = bubblesort_cpp
C_OUTPUT = bubblesort_c

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp ./$(CPP_DIR)/bubblesort.cpp -o $(CPP_OUTPUT)
	gcc ./$(C_DIR)/main.c ./$(C_DIR)/bubblesort.c -o $(C_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)
	@rm $(C_OUTPUT)