all:                                                                                                                                                                                                        
	g++ ./Cpp/main.cpp -o stack_cpp.out

clean:
	@rm -f *.out