CPPOUTPUT = stack_cpp
COUTPUT = stack_c

all:                                                                                                                                                                                                        
	g++ ./Cpp/main.cpp -o $(CPPOUTPUT)
	gcc ./C/main.c ./C/stack.c -o $(COUTPUT)

clean:
	@rm $(CPPOUTPUT)
	@rm $(COUTPUT)