CPP_DIR = Cpp
C_DIR = C

CPP_OUTPUT = binarytree_cpp

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp ./$(CPP_DIR)/binarytree.cpp -o $(CPP_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)