CPP_DIR = Cpp
C_DIR = C

CPP_OUTPUT = linkedlist_cpp
C_OUTPUT = linkedlist_c

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp ./$(CPP_DIR)/linkedlist.cpp -o $(CPP_OUTPUT)
	gcc ./$(C_DIR)/main.c ./$(C_DIR)/linkedlist.c -o $(C_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)
	@rm $(C_OUTPUT)