CPP_DIR = Cpp
C_LINTEDLIST_DIR = C

CPP_OUTPUT = linkedlist_cpp
C_LINTEDLIST_OUTPUT = linkedlist_c

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp ./$(CPP_DIR)/linkedlist.cpp -o $(CPP_OUTPUT)
	gcc ./$(C_ARRAY_DIR)/main.c ./$(C_ARRAY_DIR)/linkedlist.c -o $(C_ARRAY_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)
	@rm $(C_ARRAY_OUTPUT)