CPP_DIR = Cpp
C_DIR = C

CPP_OUTPUT = doublelinkedlist_cpp
C_OUTPUT = doublelinkedlist_c

all:                                                                                                                                                                                                        
	g++ ./$(CPP_DIR)/main.cpp ./$(CPP_DIR)/doublelinkedlist.cpp -o $(CPP_OUTPUT)
	gcc ./$(C_DIR)/main.c ./$(C_DIR)/doublelinkedlist.c -o $(C_OUTPUT)

clean:
	@rm $(CPP_OUTPUT)
	@rm $(C_OUTPUT)